# Forked from https://github.com/containerd/nerdctl/blob/main/.github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: true
contact_links:
  - name: Ask a question (GitHub Discussions)
    url: https://github.com/opencontainers/runc/discussions
    about: |
      Please do not submit "a bug report" for asking a question.
      In most cases, GitHub Discussions is the best place to ask a question.
      If you are not sure whether you are going to report a bug or ask a question,
      please consider asking in GitHub Discussions first.
  - name: Slack (opencontainers.slack.com)
    url: https://communityinviter.com/apps/opencontainers/join-the-oci-community
    # GitHub requires the `about` property to be set
    about: Slack
  - name: Mailing list
    url: https://groups.google.com/a/opencontainers.org/forum/#!forum/dev
    about: Mailing list
